on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: testthat

jobs:
  testthat:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages(c("devtools", "covr", "remotes", "withr", "testthat"))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-2-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages(c("Bergm", "RSiena", "fastglm", "ggplot2"))
        shell: Rscript {0}

      - name: Unit testing
        run: withr::with_envvar(c("NOT_CRAN" = "true"), devtools::test())
        shell: Rscript {0}

      - name: Test coverage
        run: withr::with_envvar(c("NOT_CRAN" = "true"), covr::codecov(quiet = FALSE))
        shell: Rscript {0}
